baseurl: https://fritzvd.com/blog/
disablePathToLower: true
languageCode: en-us
title: fritzvd
theme: paper
publishDir: docs/
permalinks:
  post: /:year/:month/:day/:title/
markup:
  goldmark:
    renderer:
      unsafe: true
